import type { Metadata } from "next";
import { Header } from "./components/Header";
import "./globals.css";
import connectToDbIfNot from "@/app/middlewares/connectToDbIfNot";

export const metadata: Metadata = {
  title: "Shop",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await connectToDbIfNot();
  return (
    <html lang="fr">
      <body className="max-w-5xl mx-auto">
        <Header />
        {children}
      </body>
    </html>
  );
}
